# action.yml
name: "AutoCorrect"
description: "Run AutoCorrect lint to checking copywriting."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for autocorrect"
    required: false
    default: "./ --lint"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
