# action.yml
name: "AutoCorrect"
description: "Run AutoCorrect Lint to checking copywriting."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for AutoCorrect"
    required: false
    default: "./ --lint --no-diff-bg-color"
  use_npm: # id of input
    description: "Use NPM version of AutoCorrect"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    USE_NPM: ${{ inputs.use_npm }}
  args:
    - ${{ inputs.args }}
