# action.yml
name: "AutoCorrect"
description: "Run AutoCorrect Lint to checking copywriting."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for AutoCorrect"
    required: false
    default: "./ --lint --no-diff-bg-color"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
