name: "AutoCorrect"
description: "Run AutoCorrect Lint to check copywriting."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for AutoCorrect"
    required: false
    default: ". --lint --no-diff-bg-color"
  use_npm: # id of input
    description: "Use NPM version of AutoCorrect"
    required: false
    default: "false"
  reviewdog:
    description: "Enable ReviewDog to report results to Pull Request"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    USE_NPM: ${{ inputs.use_npm }}
    REVIEWDOG: ${{ inputs.reviewdog }}
  args:
    - ${{ inputs.args }}