# action.yml
name: "AutoCorrect"
description: "Run AutoCorrect Lint to checking copywriting."
branding:
  icon: "check"
  color: "gray-dark"
inputs:
  args: # id of input
    description: "args for AutoCorrect"
    required: false
    default: ". --lint --no-diff-bg-color"
  use_npm: # id of input
    description: "Use NPM version of AutoCorrect"
    required: false
    default: "false"
  reviewdog:
    description: "Enable ReviewDog for report results to Pull Request"
    required: false
    default: "false"
  target:
    description: "Target directory to check"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    USE_NPM: ${{ inputs.use_npm }}
    REVIEWDOG: ${{ inputs.reviewdog }}
    TARGET: ${{ inputs.target }}
    ARGS: ${{ inputs.args }}
  args:
    - ${{ env.ARGS }}
